export default {
  Bulbasaur: { type1: 'Grass', type2: 'Poison' },
  Ivysaur: { type1: 'Grass', type2: 'Poison' },
  Venusaur: { type1: 'Grass', type2: 'Poison' },
  Charmander: { type1: 'Fire' },
  Charmeleon: { type1: 'Fire' },
  Charizard: { type1: 'Fire', type2: 'Flying' },
  Squirtle: { type1: 'Water' },
  Wartortle: { type1: 'Water' },
  Blastoise: { type1: 'Water' },
  Caterpie: { type1: 'Bug' },
  Metapod: { type1: 'Bug' },
  Butterfree: { type1: 'Bug', type2: 'Flying' },
  Weedle: { type1: 'Bug', type2: 'Poison' },
  Kakuna: { type1: 'Bug', type2: 'Poison' },
  Beedrill: { type1: 'Bug', type2: 'Poison' },
  Pidgey: { type1: 'Normal', type2: 'Flying' },
  Pidgeotto: { type1: 'Normal', type2: 'Flying' },
  Pidgeot: { type1: 'Normal', type2: 'Flying' },
  Rattata: { type1: 'Normal' },
  'Rattata (Alo)': { type1: 'Dark', type2: 'Normal' },
  Raticate: { type1: 'Normal' },
  'Raticate (Alo)': { type1: 'Dark', type2: 'Normal' },
  Spearow: { type1: 'Normal', type2: 'Flying' },
  Fearow: { type1: 'Normal', type2: 'Flying' },
  Ekans: { type1: 'Poison' },
  Arbok: { type1: 'Poison' },
  Pikachu: { type1: 'Electric' },
  Raichu: { type1: 'Electric' },
  'Raichu (Alo)': { type1: 'Electric', type2: 'Psychic' },
  Sandshrew: { type1: 'Ground' },
  'Sandshrew (Alo)': { type1: 'Ice', type2: 'Steel' },
  Sandslash: { type1: 'Ground' },
  'Sandslash (Alo)': { type1: 'Ice', type2: 'Steel' },
  'Nidoran♀': { type1: 'Poison' },
  Nidorina: { type1: 'Poison' },
  Nidoqueen: { type1: 'Poison', type2: 'Ground' },
  'Nidoran♂': { type1: 'Poison' },
  Nidorino: { type1: 'Poison' },
  Nidoking: { type1: 'Poison', type2: 'Ground' },
  Clefairy: { type1: 'Fairy' },
  Clefable: { type1: 'Fairy' },
  Vulpix: { type1: 'Fire' },
  'Vulpix (Alo)': { type1: 'Ice' },
  Ninetales: { type1: 'Fire' },
  'Ninetales (Alo)': { type1: 'Ice', type2: 'Fairy' },
  Jigglypuff: { type1: 'Normal', type2: 'Fairy' },
  Wigglytuff: { type1: 'Normal', type2: 'Fairy' },
  Zubat: { type1: 'Poison', type2: 'Flying' },
  Golbat: { type1: 'Poison', type2: 'Flying' },
  Oddish: { type1: 'Grass', type2: 'Poison' },
  Gloom: { type1: 'Grass', type2: 'Poison' },
  Vileplume: { type1: 'Grass', type2: 'Poison' },
  Paras: { type1: 'Bug', type2: 'Grass' },
  Parasect: { type1: 'Bug', type2: 'Grass' },
  Venonat: { type1: 'Bug', type2: 'Poison' },
  Venomoth: { type1: 'Bug', type2: 'Poison' },
  Diglett: { type1: 'Ground' },
  'Diglett (Alo)': { type1: 'Ground', type2: 'Steel' },
  Dugtrio: { type1: 'Ground' },
  'Dugtrio (Alo)': { type1: 'Ground', type2: 'Steel' },
  Meowth: { type1: 'Normal' },
  'Meowth (Alo)': { type1: 'Dark' },
  Persian: { type1: 'Normal' },
  'Persian (Alo)': { type1: 'Dark' },
  Psyduck: { type1: 'Water' },
  Golduck: { type1: 'Water' },
  Mankey: { type1: 'Fighting' },
  Primeape: { type1: 'Fighting' },
  Growlithe: { type1: 'Fire' },
  Arcanine: { type1: 'Fire' },
  Poliwag: { type1: 'Water' },
  Poliwhirl: { type1: 'Water' },
  Poliwrath: { type1: 'Water', type2: 'Fighting' },
  Abra: { type1: 'Psychic' },
  Kadabra: { type1: 'Psychic' },
  Alakazam: { type1: 'Psychic' },
  Machop: { type1: 'Fighting' },
  Machoke: { type1: 'Fighting' },
  Machamp: { type1: 'Fighting' },
  Bellsprout: { type1: 'Grass', type2: 'Poison' },
  Weepinbell: { type1: 'Grass', type2: 'Poison' },
  Victreebel: { type1: 'Grass', type2: 'Poison' },
  Tentacool: { type1: 'Water', type2: 'Poison' },
  Tentacruel: { type1: 'Water', type2: 'Poison' },
  Geodude: { type1: 'Rock', type2: 'Ground' },
  'Geodude (Alo)': { type1: 'Rock', type2: 'Electric' },
  Graveler: { type1: 'Rock', type2: 'Ground' },
  'Graveler (Alo)': { type1: 'Rock', type2: 'Electric' },
  Golem: { type1: 'Rock', type2: 'Ground' },
  'Golem (Alo)': { type1: 'Rock', type2: 'Electric' },
  Ponyta: { type1: 'Fire' },
  Rapidash: { type1: 'Fire' },
  Slowpoke: { type1: 'Water', type2: 'Psychic' },
  Slowbro: { type1: 'Water', type2: 'Psychic' },
  Magnemite: { type1: 'Electric', type2: 'Steel' },
  Magneton: { type1: 'Electric', type2: 'Steel' },
  "Farfetch'd": { type1: 'Normal', type2: 'Flying' },
  Doduo: { type1: 'Normal', type2: 'Flying' },
  Dodrio: { type1: 'Normal', type2: 'Flying' },
  Seel: { type1: 'Water' },
  Dewgong: { type1: 'Water', type2: 'Ice' },
  Grimer: { type1: 'Poison' },
  'Grimer (Alo)': { type1: 'Poison', type2: 'Dark' },
  Muk: { type1: 'Poison' },
  'Muk (Alo)': { type1: 'Poison', type2: 'Dark' },
  Shellder: { type1: 'Water' },
  Cloyster: { type1: 'Water', type2: 'Ice' },
  Gastly: { type1: 'Ghost', type2: 'Poison' },
  Haunter: { type1: 'Ghost', type2: 'Poison' },
  Gengar: { type1: 'Ghost', type2: 'Poison' },
  Onix: { type1: 'Rock', type2: 'Ground' },
  Drowzee: { type1: 'Psychic' },
  Hypno: { type1: 'Psychic' },
  Krabby: { type1: 'Water' },
  Kingler: { type1: 'Water' },
  Voltorb: { type1: 'Electric' },
  Electrode: { type1: 'Electric' },
  Exeggcute: { type1: 'Grass', type2: 'Psychic' },
  Exeggutor: { type1: 'Grass', type2: 'Psychic' },
  'Exeggutor (Alo)': { type1: 'Grass', type2: 'Dragon' },
  Cubone: { type1: 'Ground' },
  Marowak: { type1: 'Ground' },
  'Marowak (Alo)': { type1: 'Fire', type2: 'Ghost' },
  Hitmonlee: { type1: 'Fighting' },
  Hitmonchan: { type1: 'Fighting' },
  Lickitung: { type1: 'Normal' },
  Koffing: { type1: 'Poison' },
  Weezing: { type1: 'Poison' },
  Rhyhorn: { type1: 'Ground', type2: 'Rock' },
  Rhydon: { type1: 'Ground', type2: 'Rock' },
  Chansey: { type1: 'Normal' },
  Tangela: { type1: 'Grass' },
  Kangaskhan: { type1: 'Normal' },
  Horsea: { type1: 'Water' },
  Seadra: { type1: 'Water' },
  Goldeen: { type1: 'Water' },
  Seaking: { type1: 'Water' },
  Staryu: { type1: 'Water' },
  Starmie: { type1: 'Water', type2: 'Psychic' },
  'Mr. Mime': { type1: 'Psychic', type2: 'Fairy' },
  Scyther: { type1: 'Bug', type2: 'Flying' },
  Jynx: { type1: 'Ice', type2: 'Psychic' },
  Electabuzz: { type1: 'Electric' },
  Magmar: { type1: 'Fire' },
  Pinsir: { type1: 'Bug' },
  Tauros: { type1: 'Normal' },
  Magikarp: { type1: 'Water' },
  Gyarados: { type1: 'Water', type2: 'Flying' },
  Lapras: { type1: 'Water', type2: 'Ice' },
  Ditto: { type1: 'Normal' },
  Eevee: { type1: 'Normal' },
  Vaporeon: { type1: 'Water' },
  Jolteon: { type1: 'Electric' },
  Flareon: { type1: 'Fire' },
  Porygon: { type1: 'Normal' },
  Omanyte: { type1: 'Rock', type2: 'Water' },
  Omastar: { type1: 'Rock', type2: 'Water' },
  Kabuto: { type1: 'Rock', type2: 'Water' },
  Kabutops: { type1: 'Rock', type2: 'Water' },
  Aerodactyl: { type1: 'Rock', type2: 'Flying' },
  Snorlax: { type1: 'Normal' },
  Articuno: { type1: 'Ice', type2: 'Flying' },
  Zapdos: { type1: 'Electric', type2: 'Flying' },
  Moltres: { type1: 'Fire', type2: 'Flying' },
  Dratini: { type1: 'Dragon' },
  Dragonair: { type1: 'Dragon' },
  Dragonite: { type1: 'Dragon', type2: 'Flying' },
  Mewtwo: { type1: 'Psychic' },
  Mew: { type1: 'Psychic' } ,
}